### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by monza258** [anhem/lametric-hue-temperature#2] opened 2019-08-03 06:44 UTC
Hey, 

I can't start it I get an error. Do you know what's wrong:

`(function (exports, require, module, __filename, __dirname) { import hueService from "./hueService";
                                                                     ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)`

**Comment by anhem** [comment] 2019-08-07 13:16
I had some issues starting this on my Windows machine so I did the lazy thing and updated all dependencies to latest versions. Do a "git pull" and try again. 

If it still isn't working, try with the same node and npm versions I use.
node: v10.16.2
npm: 6.9.0

I've tested this on both Windows 10 and Ubuntu 18.04

**Comment by monza258** [comment] 2019-10-24 19:56
Hey. I have checked again and I don't know what I can do about this error. Do you have any idea? 

`pi@raspberrypi3:~ $ ./lametric-hue-temperature.cron.sh
(node:7274) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at /home/pi/lametric-hue-temperature/dist/hueService.js:30:55
    at Array.map (<anonymous>)
    at addSensorName (/home/pi/lametric-hue-temperature/dist/hueService.js:27:31)
    at /home/pi/lametric-hue-temperature/dist/hueService.js:45:46
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7274) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7274) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by sschuste** [comment] 2019-10-28 12:37
This happens in:
```
function addSensorName(temperatureSensors, sensors) {
    return temperatureSensors.map(temperatureSensor => {
        const sensorId = parseInt(temperatureSensor[0]);
        const siblingSensor = sensors[sensorId + 1];
        temperatureSensor[1]['sname'] = siblingSensor.name;
        return temperatureSensor;
    });
}
```

when there is no "siblingSensor" aka sensorId +1. In this case the property siblingSensor.name is undefined and the script exits. At this point an _if_ condition would help to check siblingSensor not to be empty.

**Comment by anhem** [comment] 2019-11-07 21:00
try it now, it should have a fallback for the name to fix that issue

**Comment by monza258** [comment] 2020-01-12 16:16
I use 4 Sensors now and I have 2 Sensors that shows the name “SP” on my LaMetric. 
I don’t know why. I don’t have any rooms or sensors with name SP. Is there any option to change the names? I have delete those sensors from Bridge but it’s the same name.

**Comment by anhem** [comment] 2020-01-16 17:57
names are based on the two first characters of the sensor name. 

If you have one sensor named "Bed Room Ceiling" and another named "Bed Room Window" they will both show up with the same name "BE"

**Comment by anhem** [comment] 2020-01-16 17:59
Also,

The Philips Hue API is very limited as far as I know.

The issue is that each Hue Motion Sensor is treated as multiple sensors by the bridge. One for motion, one for temperature etc. The name you give the Hue Motion Sensor is only assigned to one of these "virtual" sensors. As a best effort to get the proper name I've had to do some bad assumptions. in a sense I am guessing what the name of the sensor is. If the name cannot be found a number is assigned instead.

If you still can't get the names assigned properly you can try resetting _everything_. Reset the hue bridge and re-add sensors and then all lights. No guarantee that it will work though.

**Closed as completed** 2020-01-16 18:00 UTC
